mpc_planner:
  logarithmic:
    Q_weights: [10.0, 10.0, 0.0]
    R_weights: [1.0, 10.0]
    P_weights: [30.0, 30.0, 0.0]
    alfa: [1.0]
    beta: [0.1]

  square:
    Q_weights: [10.0, 10.0, 5.0]
    R_weights: [1.0, 10.0]
    P_weights: [30.0, 30.0, 0.0]
    alfa: [0.0]
    beta: [0.0]

robot_size:
  length: 1.6 # Simulations: 1.6 m
  width: 0.8 # Simulations: 0.8 m