mpc_planner:
  Q_weights: [
    5.0,          # x       -   default = 10.0
    5.0,          # y       -   default = 10.0
    5.0           # theta   -   default = 5.0 
    ]      
  R_weights: [
    1.0,          # v       -   default = 1.0
    10.0          # omega   -   default = 10.0
    ]
  P_weights: [
    100.0,         # x       -   default = 30.0
    100.0,         # y       -   default = 30.0
    0.0           # theta   -   default = 0.0
    ]      
  alfa: [1.0]
  beta: [0.1]
