mpc_planner:
  Q_weights: [1.0, 1.0, 5.0]   # weight for x,y,theta
  R_weights: [1.0, 5.0]          # weight for v,omega
  P_weights: [20.0, 20.0, 0.0]   # weight for x,y,theta
  alfa: [1.0]
  beta: [0.1]
