controller_frequency: 5 
controller_patience: 3

planner_frequency: 0
planner_patience: 5 

oscillation_timeout: 10
oscillation_distance: 0.2

base_local_planner: "apf_planner/ApfPlanner"
base_global_planner: "navfn/NavfnROS"